/**
 * Custom Worker entry: wraps the OpenNext-generated handler and adds a
 * `scheduled` handler for the cron triggers declared in wrangler.jsonc.
 * (@opennextjs/cloudflare does not forward scheduled events itself, so the
 * every-15-minutes trigger was firing into the void.)
 *
 * Every 15 minutes:
 *  1. IBKR history backfill — one 365-day window per user with saved
 *     credentials and an incomplete backfill (well inside IBKR's
 *     1/sec + 10/min per-token limits).
 *  2. Price-alert check — pings the secret-gated /api/alerts/check route
 *     (this was the trigger's original purpose; also previously dead).
 */

// @ts-expect-error — generated by `opennextjs-cloudflare build`; absent at typecheck time.
import openNextWorker from "./.open-next/worker.js";

import type {
  D1Database,
  ExecutionContext,
  ScheduledEvent,
} from "@cloudflare/workers-types";
import { createD1Db } from "./src/server/d1db";
import { runBackfillWindow } from "./src/server/ibkr-backfill";
import { decryptCredentials } from "./src/server/crypto";

interface BackfillUser {
  userId: string;
  iv: string;
  encToken: string;
  encQueryId: string;
}

async function runBackfillTick(env: CloudflareEnv): Promise<void> {
  const d1 = env.DB as D1Database | undefined;
  if (!d1) {
    console.log("backfill tick: no D1 binding");
    return;
  }
  // Users with saved IBKR credentials whose backfill hasn't finished
  // (no row yet, or doneAt still null).
  const { results } = await d1
    .prepare(
      `SELECT c."userId", c."iv", c."encToken", c."encQueryId"
       FROM "BrokerCredential" c
       LEFT JOIN "BrokerBackfill" b ON b."userId" = c."userId"
       WHERE b."doneAt" IS NULL`,
    )
    .all<BackfillUser>();
  if (results.length === 0) {
    console.log("backfill tick: nothing to do");
    return;
  }
  const db = createD1Db(d1);
  for (const u of results) {
    try {
      const { token, queryId } = await decryptCredentials(
        u.iv,
        u.encToken,
        u.encQueryId,
      );
      // No fresh positions in cron context; the merge only uses them for
      // repair anchoring, which the next interactive sync will handle.
      const p = await runBackfillWindow(
        db,
        { userId: u.userId, token, queryId, positions: [] },
      );
      console.log(
        `backfill tick: user ${u.userId} done=${p.done} ` +
          `window=${p.windowFetched ? `${p.windowFetched.fd}..${p.windowFetched.td}` : "-"} ` +
          `trades=${p.tradesFetched} cashFlows=${p.cashFlowsStored}` +
          (p.error ? ` error=${p.error}` : ""),
      );
    } catch (e) {
      console.error(`backfill tick: user ${u.userId} failed:`, e);
    }
    // Gentle pacing between users (IBKR: 1 req/sec per token).
    await new Promise((r) => setTimeout(r, 2000));
  }
}

async function runAlertsTick(env: CloudflareEnv): Promise<void> {
  const key = env.ALERTS_CRON_KEY;
  if (!key) {
    console.log("alerts tick: ALERTS_CRON_KEY not configured, skipping");
    return;
  }
  const base = env.NEXTAUTH_URL ?? "https://holdr.lol";
  try {
    const res = await fetch(
      `${base}/api/alerts/check?key=${encodeURIComponent(key)}`,
    );
    console.log(`alerts tick: ${res.status}`);
  } catch (e) {
    console.error("alerts tick failed:", e);
  }
}

const worker = openNextWorker as unknown as {
  fetch: (
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ) => Promise<Response>;
};

export default {
  fetch: worker.fetch,
  async scheduled(
    _event: ScheduledEvent,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<void> {
    // crypto.ts reads the key via getCloudflareContext() (throws outside a
    // request) then process.env — sync it like auth.ts does per request.
    if (env.CREDENTIALS_KEY) {
      process.env.CREDENTIALS_KEY = env.CREDENTIALS_KEY;
    }
    ctx.waitUntil(
      (async () => {
        await runBackfillTick(env);
        await runAlertsTick(env);
      })(),
    );
  },
};
